spring:
  data:
    cassandra:
      cluster-name: My Cluster
      contact-points: 34.93.81.253
      keyspace-name: show_time
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      consistency-level: ONE
      connect-timeout: 10000ms
      read-timeout: 10000ms
      pool:
        pool-timeout: 10000ms