#Application Name
spring:
  application:
    name: user-service 
  cloud:
    config:
      uri: http://localhost:8888




# Security
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9100/oauth/check_token
    client:
      client-id: show-time-booking-client
      client-secret: hack-pro-show-time-web  